name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  EB_VERSION_LABEL: ci-demo-${{github.run_number}}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: node setup
      uses: actions/setup-node@v3.7.0
      with:
        node-version: '20.3.1'

    - name: install dependencies
      run: npm ci

    - name: test
      run: npm test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: package
      run: zip -r deploy.zip . -x '*.git*'

    - name: deploy
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        application_name: ci-demo
        environment_name: ci-demo-env

        version_label: {{ env.EB_VERSION_LABEL }}
        region: "eu-north-1"
        deployment_package: deploy.zip
