name: test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: node setup
      uses: actions/setup-node@v3.7.0
      with:
        node-version: '20.3.1'
    - name: install dependencies
      run: npm ci
    - name: test
      run: npm test
